apiVersion: v1
kind: Secret
metadata:
  name: order-service-secret
  namespace: order-service
  labels:
    app.kubernetes.io/name: go-order-service
    app.kubernetes.io/part-of: go-order-service
type: Opaque
stringData:
  DATABASE_URL: "postgres://orderservice:change-me@postgres:5432/order_service?sslmode=disable"
  POSTGRES_PASSWORD: "change-me"
  JWT_SECRET: "change-me-to-a-long-random-secret"
  GRAFANA_ADMIN_USER: "admin"
  GRAFANA_ADMIN_PASSWORD: "change-me"
