apiVersion: v1
kind: Service
metadata:
  name: publisher
  labels:
    app.kubernetes.io/name: go-order-service
    app.kubernetes.io/component: publisher
    app.kubernetes.io/part-of: go-order-service
spec:
  selector:
    app.kubernetes.io/name: go-order-service
    app.kubernetes.io/component: publisher
  ports:
    - name: metrics
      port: 8081
      targetPort: metrics
      protocol: TCP
