apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: go-order-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
