apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: go-order-service
spec:
  selector:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: monitoring
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
