apiVersion: v1
kind: Service
metadata:
  name: consumer
  labels:
    app.kubernetes.io/name: go-order-service
    app.kubernetes.io/component: consumer
    app.kubernetes.io/part-of: go-order-service
spec:
  selector:
    app.kubernetes.io/name: go-order-service
    app.kubernetes.io/component: consumer
  ports:
    - name: metrics
      port: 8082
      targetPort: metrics
      protocol: TCP
