apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/component: messaging
    app.kubernetes.io/part-of: go-order-service
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/component: messaging
  ports:
    - name: internal
      port: 29092
      targetPort: internal
      protocol: TCP
    - name: controller
      port: 9093
      targetPort: controller
      protocol: TCP
