apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: order-service

resources:
  - ../../base
  - redirect-https.yaml
  - frontend.yaml

patches:
  - path: configmap-patch.yaml
    target:
      version: v1
      kind: ConfigMap
      name: order-service-config
  - path: ingress-patch.yaml
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: api
