// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIdempotencyKey = `-- name: CreateIdempotencyKey :one
INSERT INTO idempotency_keys (
    id,
    user_id,
    key,
    method,
    path,
    request_hash,
    response_body,
    status_code,
    resource_type,
    resource_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, user_id, key, method, path, request_hash, response_body, status_code, resource_type, resource_id, created_at
`

type CreateIdempotencyKeyParams struct {
	ID           pgtype.UUID `json:"id"`
	UserID       pgtype.UUID `json:"user_id"`
	Key          string      `json:"key"`
	Method       string      `json:"method"`
	Path         string      `json:"path"`
	RequestHash  string      `json:"request_hash"`
	ResponseBody []byte      `json:"response_body"`
	StatusCode   pgtype.Int4 `json:"status_code"`
	ResourceType pgtype.Text `json:"resource_type"`
	ResourceID   pgtype.UUID `json:"resource_id"`
}

func (q *Queries) CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, createIdempotencyKey,
		arg.ID,
		arg.UserID,
		arg.Key,
		arg.Method,
		arg.Path,
		arg.RequestHash,
		arg.ResponseBody,
		arg.StatusCode,
		arg.ResourceType,
		arg.ResourceID,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Key,
		&i.Method,
		&i.Path,
		&i.RequestHash,
		&i.ResponseBody,
		&i.StatusCode,
		&i.ResourceType,
		&i.ResourceID,
		&i.CreatedAt,
	)
	return i, err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT id, user_id, key, method, path, request_hash, response_body, status_code, resource_type, resource_id, created_at
FROM idempotency_keys
WHERE user_id = $1
  AND key = $2
`

type GetIdempotencyKeyParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Key    string      `json:"key"`
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.UserID, arg.Key)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Key,
		&i.Method,
		&i.Path,
		&i.RequestHash,
		&i.ResponseBody,
		&i.StatusCode,
		&i.ResourceType,
		&i.ResourceID,
		&i.CreatedAt,
	)
	return i, err
}
