// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type IdempotencyKey struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Key          string             `json:"key"`
	Method       string             `json:"method"`
	Path         string             `json:"path"`
	RequestHash  string             `json:"request_hash"`
	ResponseBody []byte             `json:"response_body"`
	StatusCode   pgtype.Int4        `json:"status_code"`
	ResourceType pgtype.Text        `json:"resource_type"`
	ResourceID   pgtype.UUID        `json:"resource_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type NotificationDelivery struct {
	ID        pgtype.UUID        `json:"id"`
	EventID   pgtype.UUID        `json:"event_id"`
	Channel   string             `json:"channel"`
	Recipient string             `json:"recipient"`
	Status    string             `json:"status"`
	Attempt   int32              `json:"attempt"`
	LastError pgtype.Text        `json:"last_error"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Order struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Status      string             `json:"status"`
	AmountCents int64              `json:"amount_cents"`
	Currency    string             `json:"currency"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type OutboxEvent struct {
	ID            pgtype.UUID        `json:"id"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   pgtype.UUID        `json:"aggregate_id"`
	EventType     string             `json:"event_type"`
	Payload       []byte             `json:"payload"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	Attempt       int32              `json:"attempt"`
	LastError     pgtype.Text        `json:"last_error"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Payment struct {
	ID            pgtype.UUID        `json:"id"`
	OrderID       pgtype.UUID        `json:"order_id"`
	Status        string             `json:"status"`
	AmountCents   int64              `json:"amount_cents"`
	Provider      string             `json:"provider"`
	ProviderRef   pgtype.Text        `json:"provider_ref"`
	FailureReason pgtype.Text        `json:"failure_reason"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type ProcessedEvent struct {
	EventID      pgtype.UUID        `json:"event_id"`
	ConsumerName string             `json:"consumer_name"`
	ProcessedAt  pgtype.Timestamptz `json:"processed_at"`
}

type RefreshToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
