// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification_deliveries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNotificationDelivery = `-- name: CreateNotificationDelivery :one
INSERT INTO notification_deliveries (
    id,
    event_id,
    channel,
    recipient,
    status
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, event_id, channel, recipient, status, attempt, last_error, created_at, updated_at
`

type CreateNotificationDeliveryParams struct {
	ID        pgtype.UUID `json:"id"`
	EventID   pgtype.UUID `json:"event_id"`
	Channel   string      `json:"channel"`
	Recipient string      `json:"recipient"`
	Status    string      `json:"status"`
}

func (q *Queries) CreateNotificationDelivery(ctx context.Context, arg CreateNotificationDeliveryParams) (NotificationDelivery, error) {
	row := q.db.QueryRow(ctx, createNotificationDelivery,
		arg.ID,
		arg.EventID,
		arg.Channel,
		arg.Recipient,
		arg.Status,
	)
	var i NotificationDelivery
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Channel,
		&i.Recipient,
		&i.Status,
		&i.Attempt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
