// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
    id,
    order_id,
    status,
    amount_cents,
    provider,
    provider_ref,
    failure_reason
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, order_id, status, amount_cents, provider, provider_ref, failure_reason, created_at, updated_at
`

type CreatePaymentParams struct {
	ID            pgtype.UUID `json:"id"`
	OrderID       pgtype.UUID `json:"order_id"`
	Status        string      `json:"status"`
	AmountCents   int64       `json:"amount_cents"`
	Provider      string      `json:"provider"`
	ProviderRef   pgtype.Text `json:"provider_ref"`
	FailureReason pgtype.Text `json:"failure_reason"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.ID,
		arg.OrderID,
		arg.Status,
		arg.AmountCents,
		arg.Provider,
		arg.ProviderRef,
		arg.FailureReason,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Status,
		&i.AmountCents,
		&i.Provider,
		&i.ProviderRef,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPayment = `-- name: GetPayment :one
SELECT id, order_id, status, amount_cents, provider, provider_ref, failure_reason, created_at, updated_at
FROM payments
WHERE id = $1
`

func (q *Queries) GetPayment(ctx context.Context, id pgtype.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Status,
		&i.AmountCents,
		&i.Provider,
		&i.ProviderRef,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
