// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: processed_events.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const tryCreateProcessedEvent = `-- name: TryCreateProcessedEvent :one
INSERT INTO processed_events (
    event_id,
    consumer_name
) VALUES (
    $1, $2
)
ON CONFLICT DO NOTHING
RETURNING event_id, consumer_name, processed_at
`

type TryCreateProcessedEventParams struct {
	EventID      pgtype.UUID `json:"event_id"`
	ConsumerName string      `json:"consumer_name"`
}

func (q *Queries) TryCreateProcessedEvent(ctx context.Context, arg TryCreateProcessedEventParams) (ProcessedEvent, error) {
	row := q.db.QueryRow(ctx, tryCreateProcessedEvent, arg.EventID, arg.ConsumerName)
	var i ProcessedEvent
	err := row.Scan(&i.EventID, &i.ConsumerName, &i.ProcessedAt)
	return i, err
}
